version: "2"

volumes:
  db-data:
    driver: local

services:
    python-mad-postgres:
        image: postgres:9.6
        container_name: python-mad-postgres
        volumes:
            - ./db-data:/var/lib/postgresql/data
        env_file: src/.env
        networks:
            - python-mad-network


    python-mad-web:
        build:
            context: .
            dockerfile: docker/back
        image: python-mad-web:1.0
        container_name: python-mad-web
        command: bash -c "/venv/bin/python manage.py migrate && /venv/bin/python manage.py collectstatic --noinput && /venv/bin/gunicorn -w 6 -t 60 -b 0.0.0.0:5040 wsgi --access-logfile gunicorn-access-log --error-logfile gunicorn-error-log --log-level debug"
        #command: bash -c "touch fiile && tail -f fiile"
        volumes:
            - ./src/static:/python-mad-web/static
            - ./src/media:/python-mad-web/media
        networks:
            - python-mad-network
        depends_on:
            - python-mad-postgres


    python-mad-nginx:
        build:
            context: .
            dockerfile: docker/nginx
        image: python-mad-nginx:1.0
        container_name: python-mad-nginx
        ports:
            - "5004:5004"
        networks:
            - python-mad-network
        depends_on:
            - python-mad-web
        volumes:
            - ./src/static:/python-mad-web/static


networks:
  python-mad-network:
    driver: bridge

